name: joblance_firebase
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.3+3

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  advance_notification: ^1.0.6
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  dots_indicator: ^2.1.0
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_feather_icons: ^2.0.0+1
  flutter_iconly: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.3
  http: ^0.13.5
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  octo_image: ^1.0.2
  path: ^1.8.2
  pin_input_text_field: ^4.2.0
  readmore: ^2.2.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0-nullsafety.0
  timeago: ^3.3.0
  timer_count_down: ^2.2.1
  url_launcher: ^6.1.7
  very_good_analysis: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - json_file/
